set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OceanBase Plugins")
set(CPACK_PACKAGE_VENDOR "OceanBase Inc.")
set(CPACK_PACKAGE_DESCRIPTION "OceanBase Plugins")
# This is the prefix of plugin package name, such as oceanbase-plugin-jieba-ftparser
set(CPACK_PACKAGE_NAME "oceanbase-plugin")
set(CPACK_PACKAGE_CONTACT "https://open.oceanbase.com")

#set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR}) # CMAKE_PROJECT_VERSION_MAJOR
#set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR}) # CMAKE_PROJECT_VERSION_MINOR
#set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH}) # CMAKE_PROJECT_VERSION_PATCH
#set(CPACK_PACKAGE_VERSION       ${PROJECT_VERSION})
set(CPACK_PACKAGE_RELOCATABLE ON)

# set a default release number
if(NOT DEFINED PACKAGE_RELEASE)
  set(PACKAGE_RELEASE 1)
endif()

set(CPACK_COMPONENTS_ALL ${PACK_COMPONENTS})

set(CPACK_RPM_PACKAGE_LICENSE "Apache-2.0")
set(CPACK_RPM_PACKAGE_GROUP   "Applications/Databases")
set(CPACK_RPM_FILE_NAME       "RPM-DEFAULT")
set(CPACK_RPM_PACKAGE_RELEASE ${PACKAGE_RELEASE})
message(STATUS "CPACK_RPM_PACKAGE_RELEASE is ${CPACK_RPM_PACKAGE_RELEASE}")
# RPM doesn't support this changelog format
# set(CPACK_RPM_CHANGELOG_FILE ${PROJECT_SOURCE_DIR}/CHANGELOG.md)
set(CPACK_RPM_COMPONENT_INSTALL ON)

set(CPACK_DEBIAN_FILE_NAME          DEB-DEFAULT)
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "OceanBase")
set(CPACK_DEBIAN_PACKAGE_SECTION    "database")
set(CPACK_DEBIAN_PACKAGE_PRIORITY   "optional")
set(CPACK_DEBIAN_PACKAGE_RELEASE    ${PACKAGE_RELEASE})
message(STATUS "CPACK_DEBIAN_PACKAGE_RELEASE is ${CPACK_DEBIAN_PACKAGE_RELEASE}")
set(CPACK_DEB_COMPONENT_INSTALL ON)

include(CPack)

